/*

AUTOGENERATED KERNEL
Settings:
 LMUL=1
 M=8
 M_tail_scalar_from=2
 N=8
 __riscv_='__riscv_'
 complex=False
 conjugate=False
 cpu='zvl256b'
 force_acc_double=False
 index_type='BLASLONG'
 op='gemm'
 param_precision='double'
 reg_width_bits=256
 tail_policy=''
 trace=False

Derived:
 ELEN_ACC=64
 ELEN_PARAM=64
 LMUL_ACC=1
 VFMACC='__riscv_vfmacc_vf_f64m1'
 VFMUL='__riscv_vfmul_vf_f64m1'
 VLEV='__riscv_vle64_v_f64m1'
 VLSEV='__riscv_vlse64_v_f64m1'
 VMACC_TO_ACC='__riscv_vfmacc_vf_f64m1'
 VMUL_TO_ACC='__riscv_vfmul_vf_f64m1'
 VSETVL='__riscv_vsetvl_e64m1'
 VSEV='__riscv_vse64_v_f64m1'
 VSSEV='__riscv_vsse64_v_f64m1'
 acc_vector_t='vfloat64m1_t'
 output='dgemm_kernel_8x8_zvl256b.c'
 param_scalar_t='double'
 param_vector_t='vfloat64m1_t'

*/

#include "common.h"

static inline void X80_n8xm8_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);
static inline void X80_n4xm8_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);
static inline void X80_n2xm8_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);
static inline void X80_n1xm8_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);
static inline void X80_n8xm4_kernel(BLASLONG m, BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);
static inline void X80_n4xm4_kernel(BLASLONG m, BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);
static inline void X80_n2xm4_kernel(BLASLONG m, BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);
static inline void X80_n1xm4_kernel(BLASLONG m, BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);
static inline void X80_n8xm1_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);
static inline void X80_n4xm1_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);
static inline void X80_n2xm1_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc);

static inline void X80_dot_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C);

int CNAME(BLASLONG bm, BLASLONG bn, BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc)
{
    // for(BLASLONG j = 0; j < bn; j+=8){
    //     for(BLASLONG i = 0; i < bm; i+=8){
    //         for(BLASLONG k = 0; k < bk; ++k){
    //             for(BLASLONG bj = 0; bj < 8; ++bj){
    //                 for(BLASLONG bi = 0; bi < 8; ++bi){
    //                     C[(j+bj)*ldc+(i+bi)] += alpha * A[i*bk+k*8+bi] * B[j*bk+k*8+bj];
    //                 }
    //             }
    //         }
    //     }
    // }

    //printf("m:%ld, n:%ld, k:%ld, C:%ld\n", bm, bn, bk, C);
    // -- MAIN PASS
    for(BLASLONG bj = 0; bj < bn/8; ++bj){
        BLASLONG j = bj * 8;
        for(BLASLONG bi = 0; bi < bm/8; ++bi){
            BLASLONG i = bi * 8;
            X80_n8xm8_kernel(bk, alpha, &A[i*bk], &B[j*bk], &C[j*ldc+i], ldc);
        }
        if(bm & 4) X80_n8xm4_kernel(4, bk, alpha, &A[(bm&(~7ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~7ULL))], ldc);
        if(bm & 2) X80_n8xm4_kernel(2, bk, alpha, &A[(bm&(~3ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~3ULL))], ldc);
        if(bm & 1) X80_n8xm1_kernel(bk, alpha, &A[(bm&(~1ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~1ULL))], ldc);
    }

    // -- FRACTIONAL PASS
    if(bn & 4){
        BLASLONG j = bn&(~7ULL);
        for(BLASLONG bi = 0; bi < bm/8; ++bi){
            BLASLONG i = bi * 8;
            X80_n4xm8_kernel(bk, alpha, &A[i*bk], &B[j*bk], &C[j*ldc+i], ldc);
        }
        
        if(bm & 4) X80_n4xm4_kernel(4, bk, alpha, &A[(bm&(~7ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~7ULL))], ldc);
        if(bm & 2) X80_n4xm4_kernel(2, bk, alpha, &A[(bm&(~3ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~3ULL))], ldc);
        if(bm & 1) X80_n4xm1_kernel(bk, alpha, &A[(bm&(~1ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~1ULL))], ldc);
    }
    if(bn & 2){
        BLASLONG j = bn&(~3ULL);
        for(BLASLONG bi = 0; bi < bm/8; ++bi){
            BLASLONG i = bi * 8;
            X80_n2xm8_kernel(bk, alpha, &A[i*bk], &B[j*bk], &C[j*ldc+i], ldc);
        }
        
        if(bm & 4) X80_n2xm4_kernel(4, bk, alpha, &A[(bm&(~7ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~7ULL))], ldc);
        if(bm & 2) X80_n2xm4_kernel(2, bk, alpha, &A[(bm&(~3ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~3ULL))], ldc);
        if(bm & 1) X80_n2xm1_kernel(bk, alpha, &A[(bm&(~1ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~1ULL))], ldc);
    }
    if(bn & 1){
        BLASLONG j = bn&(~1ULL);
        for(BLASLONG bi = 0; bi < bm/8; ++bi){
            BLASLONG i = bi * 8;
            X80_n1xm8_kernel(bk, alpha, &A[i*bk], &B[j*bk], &C[j*ldc+i], ldc);
        }
        if(bm & 4) X80_n1xm4_kernel(4, bk, alpha, &A[(bm&(~7ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~7ULL))], ldc);
        if(bm & 2) X80_n1xm4_kernel(2, bk, alpha, &A[(bm&(~3ULL))*bk], &B[j*bk], &C[j*ldc+(bm&(~3ULL))], ldc);
        if(bm & 1){
            BLASLONG i = bm&(~1ULL);
            X80_dot_kernel(bk, alpha, &A[i*bk], &B[j*bk], &C[j*ldc+i]);
        }
    }

    return 0;
}

static inline void X80_n8xm8_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetivli   zero,4,e64,m1,ta,ma;"
        "addi     t6, %[A], 32;" // a1 addr
        "vle64.v    v30, (%[A]);" // a0
        "addi       %[A], %[A], 64;" // next a0 addr
        "vle64.v    v31, (t6);"   // a1
        "addi       t6, t6, 64;"     // next a1 addr
        "fld        ft0,   (%[B]);" // b0
        "fld        ft1,  8(%[B]);" // b1
        "addi       %[bk], %[bk], -1;" // loop var

        "fld        ft2, 16(%[B]);" // b2
        "vfmul.vf   v0, v30, ft0;"
        "vfmul.vf   v1, v31, ft0;"

        "fld        ft3, 24(%[B]);" // b3
        "vfmul.vf   v2, v30, ft1;"
        "vfmul.vf   v3, v31, ft1;"

        "fld        ft4, 32(%[B]);" // b4
        "vfmul.vf   v4, v30, ft2;"
        "vfmul.vf   v5, v31, ft2;"
        
        "fld        ft5, 40(%[B]);" // b5
        "vfmul.vf   v6, v30, ft3;"
        "vfmul.vf   v7, v31, ft3;"
        
        "fld        ft6, 48(%[B]);" // b6
        "vfmul.vf   v8, v30, ft4;"
        "vfmul.vf   v9, v31, ft4;"
        
        "fld        ft7, 56(%[B]);" // b7
        "vfmul.vf  v10, v30, ft5;"
        "vfmul.vf  v11, v31, ft5;"
        
        "addi       %[B], %[B], 64;" // next b addr
        "vfmul.vf  v12, v30, ft6;"
        "vfmul.vf  v13, v31, ft6;"

        "vfmul.vf  v14, v30, ft7;"
        "vfmul.vf  v15, v31, ft7;"

        "dgemm_8x8_asm_1k_loop%=:"
        "beq        %[bk], zero, dgemm_8x8_asm_1k_finish%=;"
            "vle64.v    v30,  (%[A]);  addi   %[A], %[A], 64;" // a0
            "vle64.v    v31,    (t6);  addi   t6, t6, 64;" // a1
            "fld        ft0,  (%[B]);  addi   %[bk], %[bk], -1;" // b0
            "fld        ft1,  8(%[B]);" // b1
            "vfmacc.vf   v0, ft0, v30;"
            "vfmacc.vf   v1, ft0, v31;"

            "fld        ft2, 16(%[B]);" // b2
            "vfmacc.vf   v2, ft1, v30;"
            "vfmacc.vf   v3, ft1, v31;"

            "fld        ft3, 24(%[B]);" // b3
            "vfmacc.vf   v4, ft2, v30;"
            "vfmacc.vf   v5, ft2, v31;"
            
            "fld        ft4, 32(%[B]);" // b4
            "vfmacc.vf   v6, ft3, v30;"
            "vfmacc.vf   v7, ft3, v31;"
            
            "fld        ft5, 40(%[B]);" // b5
            "vfmacc.vf   v8, ft4, v30;"
            "vfmacc.vf   v9, ft4, v31;"

            "fld        ft6, 48(%[B]);" // b6
            "vfmacc.vf  v10, ft5, v30;"
            "vfmacc.vf  v11, ft5, v31;"

            "fld        ft7, 56(%[B]);" // b7
            "vfmacc.vf  v12, ft6, v30;"
            "vfmacc.vf  v13, ft6, v31;"
            
            "vfmacc.vf  v14, ft7, v30;"
            "vfmacc.vf  v15, ft7, v31;"

            "addi       %[B], %[B], 64;" // next b addr
            "j  dgemm_8x8_asm_1k_loop%=;"

        "dgemm_8x8_asm_1k_finish%=:"

        "vle64.v    v16, (%[C]); addi    t0, %[C], 32  ;" // C0 & C1 addr
        "vle64.v    v17,  (t0) ; sh3add  t1, %[ldc], %[C];" // C1 & C2 addr
        "vle64.v    v18,  (t1) ; sh3add  t0, %[ldc], t0;" // C2 & C3 addr
        "vle64.v    v19,  (t0) ; sh3add  t1, %[ldc], t1;" // C3 & C4 addr
        "vle64.v    v20,  (t1) ; sh3add  t0, %[ldc], t0;" // C4 & C5 addr
        "vfmacc.vf v16, %[alpha], v0;"
        "vfmacc.vf v17, %[alpha], v1;"
        "vfmacc.vf v18, %[alpha], v2;"
        "vfmacc.vf v19, %[alpha], v3;"
        "vfmacc.vf v20, %[alpha], v4;"
        "vse64.v    v16, (%[C]); addi    t2, %[C], 32  ;" // C0 & C1 addr
        "vse64.v    v17,  (t2) ; sh3add  t3, %[ldc], %[C];" // C1 & C2 addr
        "vse64.v    v18,  (t3) ; sh3add  t2, %[ldc], t2;" // C2 & C3 addr
        "vse64.v    v19,  (t2) ; sh3add  t3, %[ldc], t3;" // C3 & C4 addr
        "vse64.v    v20,  (t3) ; sh3add  t2, %[ldc], t2;" // C4 & C5 addr

        "vle64.v    v21,  (t0) ; sh3add  t1, %[ldc], t1;" // C5 & C6 addr
        "vle64.v    v22,  (t1) ; sh3add  t0, %[ldc], t0;" // C6 & C7 addr
        "vle64.v    v23,  (t0) ; sh3add  t1, %[ldc], t1;" // C7 & C8 addr
        "vle64.v    v24,  (t1) ; sh3add  t0, %[ldc], t0;" // C8 & C9 addr
        "vle64.v    v25,  (t0) ; sh3add  t1, %[ldc], t1;" // C9 & C10 addr
        "vfmacc.vf v21, %[alpha], v5;"
        "vfmacc.vf v22, %[alpha], v6;"
        "vfmacc.vf v23, %[alpha], v7;"
        "vfmacc.vf v24, %[alpha], v8;"
        "vfmacc.vf v25, %[alpha], v9;"
        "vse64.v    v21,  (t2) ; sh3add  t3, %[ldc], t3;" // C5 & C6 addr
        "vse64.v    v22,  (t3) ; sh3add  t2, %[ldc], t2;" // C6 & C7 addr
        "vse64.v    v23,  (t2) ; sh3add  t3, %[ldc], t3;" // C7 & C8 addr
        "vse64.v    v24,  (t3) ; sh3add  t2, %[ldc], t2;" // C8 & C9 addr
        "vse64.v    v25,  (t2) ; sh3add  t3, %[ldc], t3;" // C9 & C10 addr



        "vle64.v    v26,  (t1) ; sh3add  t0, %[ldc], t0;" // C10 & C11 addr
        "vle64.v    v27,  (t0) ; sh3add  t1, %[ldc], t1;" // C11 & C12 addr
        "vle64.v    v28,  (t1) ; sh3add  t0, %[ldc], t0;" // C12 & C13 addr
        "vle64.v    v29,  (t0) ; sh3add  t1, %[ldc], t1;" // C13 & C14 addr
        "vle64.v    v30,  (t1) ; sh3add  t0, %[ldc], t0;" // C14 & C15 addr
        "vle64.v    v31,  (t0) ;" // C15
        "vfmacc.vf v26, %[alpha], v10;"
        "vfmacc.vf v27, %[alpha], v11;"
        "vfmacc.vf v28, %[alpha], v12;"
        "vfmacc.vf v29, %[alpha], v13;"
        "vfmacc.vf v30, %[alpha], v14;"
        "vfmacc.vf v31, %[alpha], v15;"
        "vse64.v    v26,  (t3) ; sh3add  t2, %[ldc], t2;" // C10 & C11 addr
        "vse64.v    v27,  (t2) ; sh3add  t3, %[ldc], t3;" // C11 & C12 addr
        "vse64.v    v28,  (t3) ; sh3add  t2, %[ldc], t2;" // C12 & C13 addr
        "vse64.v    v29,  (t2) ; sh3add  t3, %[ldc], t3;" // C13 & C14 addr
        "vse64.v    v30,  (t3) ; sh3add  t2, %[ldc], t2;" // C14 & C15 addr
        "vse64.v    v31,  (t2) ;" // C15

        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc]"r"(ldc), [alpha]"f"(alpha)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}

static inline void X80_n8xm4_kernel(BLASLONG m, BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetvli   zero,%[m],e64,m1,ta,ma;"

        "vle64.v   v31,   (%[A]); sh3add     %[A], %[m], %[A];" // a0 & next a0 addr
        "fld       ft0,   (%[B]); addi       %[bk], %[bk], -1;" // b0 & loop var
        "fld       ft1,  8(%[B]);" // b1

        "fld       ft2, 16(%[B]) ; vfmul.vf   v0, v31, ft0;" // b2
        "fld       ft3, 24(%[B]) ; vfmul.vf   v1, v31, ft1;" // b3
        "fld       ft4, 32(%[B]) ; vfmul.vf   v2, v31, ft2;" // b4
        "fld       ft5, 40(%[B]) ; vfmul.vf   v3, v31, ft3;" // b5
        "fld       ft6, 48(%[B]) ; vfmul.vf   v4, v31, ft4;" // b6
        "fld       ft7, 56(%[B]) ; vfmul.vf   v5, v31, ft5;"  // b7
        "addi      %[B], %[B], 64; vfmul.vf   v6, v31, ft6;"  // next b addr
        "vfmul.vf  v7, v31, ft7;"
        

        "dgemm_8x4_asm_k_loop%=:"
            "beq       %[bk], zero, dgemm_8x4_asm_k_loop_finish%=;"
            "vle64.v  v31,   (%[A]) ; sh3add     %[A], %[m], %[A];" // a0 & next a0 addr
            "fld      ft0,   (%[B]);" // b0
            "fld      ft1,  8(%[B]) ; addi       %[bk], %[bk], -1;" // b1 & loop var

            "fld      ft2, 16(%[B]) ; vfmacc.vf  v0, ft0, v31;" // b2
            "fld      ft3, 24(%[B]) ; vfmacc.vf  v1, ft1, v31;" // b3
            "fld      ft4, 32(%[B]) ; vfmacc.vf  v2, ft2, v31;" // b4
            "fld      ft5, 40(%[B]) ; vfmacc.vf  v3, ft3, v31;" // b5
            "fld      ft6, 48(%[B]) ; vfmacc.vf  v4, ft4, v31;" // b6
            "fld      ft7, 56(%[B]) ; vfmacc.vf  v5, ft5, v31;" // b7
            "addi     %[B], %[B], 64; vfmacc.vf  v6, ft6, v31;" // next b addr
            "vfmacc.vf  v7, ft7, v31;"

            "j        dgemm_8x4_asm_k_loop%=;"
        "dgemm_8x4_asm_k_loop_finish%=:"

        "vle64.v    v16, (%[C]); sh3add  t0, %[ldc], %[C];" // C0 & C1 addr
        "vle64.v    v17,  (t0) ; sh3add  t0, %[ldc], t0;" // C1 & C2 addr
        "vle64.v    v18,  (t0) ; sh3add  t0, %[ldc], t0;" // C2 & C3 addr
        "vle64.v    v19,  (t0) ; sh3add  t0, %[ldc], t0;" // C3 & C4 addr
        "vle64.v    v20,  (t0) ; sh3add  t0, %[ldc], t0;" // C4 & C5 addr
        "vle64.v    v21,  (t0) ; sh3add  t0, %[ldc], t0;" // C5 & C6 addr
        "vle64.v    v22,  (t0) ; sh3add  t0, %[ldc], t0;" // C6 & C7 addr
        "vle64.v    v23,  (t0) ;" // C7

        "vfmacc.vf v16, %[alpha], v0;"
        "vfmacc.vf v17, %[alpha], v1;"
        "vfmacc.vf v18, %[alpha], v2;"
        "vfmacc.vf v19, %[alpha], v3;"
        "vfmacc.vf v20, %[alpha], v4;"
        "vfmacc.vf v21, %[alpha], v5;"
        "vfmacc.vf v22, %[alpha], v6;"
        "vfmacc.vf v23, %[alpha], v7;"

        "vse64.v    v16, (%[C]); sh3add  t0, %[ldc], %[C];" // C0 & C1 addr
        "vse64.v    v17,  (t0) ; sh3add  t0, %[ldc], t0;" // C1 & C2 addr
        "vse64.v    v18,  (t0) ; sh3add  t0, %[ldc], t0;" // C2 & C3 addr
        "vse64.v    v19,  (t0) ; sh3add  t0, %[ldc], t0;" // C3 & C4 addr
        "vse64.v    v20,  (t0) ; sh3add  t0, %[ldc], t0;" // C4 & C5 addr
        "vse64.v    v21,  (t0) ; sh3add  t0, %[ldc], t0;" // C5 & C6 addr
        "vse64.v    v22,  (t0) ; sh3add  t0, %[ldc], t0;" // C6 & C7 addr
        "vse64.v    v23,  (t0) ;" // C7

        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc]"r"(ldc), [alpha]"f"(alpha), [m]"r"(m)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}


static inline void X80_n8xm1_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetivli   zero,4,e64,m1,ta,ma;"

        "fld       ft0,  (%[A]); addi    %[A], %[A], 8;"   // a0 & next a0 addr
        "vle64.v   v30,  (%[B]); addi    %[B], %[B], 32;"  // b0 
        "vle64.v   v31,  (%[B]); addi    %[B], %[B], 32;" // b1
        "addi    %[bk], %[bk], -1;"
        "vfmul.vf  v0, v30, ft0;" // b0
        "vfmul.vf  v1, v31, ft0;" // b1

        "dgemm_8x1_asm_k_loop%=:"
            "beq       %[bk], zero, dgemm_8x1_asm_k_loop_finish%=;"
            "fld       ft0,  (%[A]) ; addi    %[A], %[A], 8;" // a0 & next a0 addr
            "vle64.v   v30,  (%[B]) ; addi    %[B], %[B], 32;"    // b0 
            "vle64.v   v31,  (%[B]) ; addi    %[B], %[B], 32;" // b1 & loop var
            "addi    %[bk], %[bk], -1;"

            "vfmacc.vf  v0, ft0, v30;" // b0
            "vfmacc.vf  v1, ft0, v31;" // b1

            "j        dgemm_8x1_asm_k_loop%=;"
        "dgemm_8x1_asm_k_loop_finish%=:"

        "slli t0, %[ldc], 3;"
        "vlse64.v  v16, (%[C]), t0;" // C0
        "slli t1, t0, 2;"
        "add  t1, %[C], t1;"
        "vlse64.v  v17, (t1), t0;" // C1
        
        "vfmacc.vf v16, %[alpha], v0;"
        "vfmacc.vf v17, %[alpha], v1;"

        "vsse64.v  v16, (%[C]), t0;" // C0
        "vsse64.v  v17, (t1), t0;" // C1
        
        
        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc]"r"(ldc), [alpha]"f"(alpha)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}


static inline void X80_n4xm8_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetivli   zero,4,e64,m1,ta,ma;"
        "addi     t6, %[A], 32;" // a1 addr

        "vle64.v    v30, (%[A]);" // a0
        "addi       %[A], %[A], 64;" // next a0 addr
        "vle64.v    v31, (t6);"   // a1
        "addi       t6, t6, 64;"     // next a1 addr
        "fld        ft0,   (%[B]);" // b0
        "fld        ft1,  8(%[B]);" // b1
        "addi       %[bk], %[bk], -1;" // loop var

        "fld        ft2, 16(%[B]);" // b2
        "vfmul.vf   v0, v30, ft0;"
        "vfmul.vf   v1, v31, ft0;"

        "fld        ft3, 24(%[B]);" // b3
        "vfmul.vf   v2, v30, ft1;"
        "vfmul.vf   v3, v31, ft1;"

        
        "addi       %[B], %[B], 32;" // next b addr
        "vfmul.vf   v4, v30, ft2;"
        "vfmul.vf   v5, v31, ft2;"

        "vfmul.vf  v6, v30, ft3;"
        "vfmul.vf  v7, v31, ft3;"
        
        "dgemm_4x8_asm_k_loop%=:"
            "beq        %[bk], zero, dgemm_4x8_asm_k_loop_finish%=;"
            "vle64.v    v30, (%[A]);" // a0
            "addi       %[A], %[A], 64;" // next a0 addr
            "vle64.v    v31, (t6);"   // a1
            "addi       t6, t6, 64;"     // next a1 addr
            "fld        ft0,   (%[B]);" // b0
            "fld        ft1,  8(%[B]);" // b1
            "addi       %[bk], %[bk], -1;" // loop var

            "fld        ft2, 16(%[B]);" // b2
            "vfmacc.vf   v0, ft0, v30;"
            "vfmacc.vf   v1, ft0, v31;"

            "fld        ft3, 24(%[B]);" // b3
            "vfmacc.vf   v2, ft1, v30;"
            "vfmacc.vf   v3, ft1, v31;"

            "addi       %[B], %[B], 32;" // next b addr
            "vfmacc.vf   v4, ft2, v30;"
            "vfmacc.vf   v5, ft2, v31;"
            
            "vfmacc.vf   v6, ft3, v30;"
            "vfmacc.vf   v7, ft3, v31;"
            
            "j           dgemm_4x8_asm_k_loop%=;"
        "dgemm_4x8_asm_k_loop_finish%=:"

        "vle64.v    v16, (%[C]); addi    t0, %[C], 32  ;" // C0 & C1 addr
        "vle64.v    v17,  (t0) ; sh3add  t1, %[ldc], %[C];" // C1 & C2 addr
        "vle64.v    v18,  (t1) ; sh3add  t0, %[ldc], t0;" // C2 & C3 addr
        "vle64.v    v19,  (t0) ; sh3add  t1, %[ldc], t1;" // C3 & C4 addr
        "vle64.v    v20,  (t1) ; sh3add  t0, %[ldc], t0;" // C4 & C5 addr
        "vle64.v    v21,  (t0) ; sh3add  t1, %[ldc], t1;" // C5 & C6 addr
        "vle64.v    v22,  (t1) ; sh3add  t0, %[ldc], t0;" // C6 & C7 addr
        "vle64.v    v23,  (t0) ;" // C7

        "vfmacc.vf v16, %[alpha], v0;"
        "vfmacc.vf v17, %[alpha], v1;"
        "vfmacc.vf v18, %[alpha], v2;"
        "vfmacc.vf v19, %[alpha], v3;"
        "vfmacc.vf v20, %[alpha], v4;"
        "vfmacc.vf v21, %[alpha], v5;"
        "vfmacc.vf v22, %[alpha], v6;"
        "vfmacc.vf v23, %[alpha], v7;"

        "vse64.v    v16, (%[C]); addi    t0, %[C], 32  ;" // C0 & C1 addr
        "vse64.v    v17,  (t0) ; sh3add  t1, %[ldc], %[C];" // C1 & C2 addr
        "vse64.v    v18,  (t1) ; sh3add  t0, %[ldc], t0;" // C2 & C3 addr
        "vse64.v    v19,  (t0) ; sh3add  t1, %[ldc], t1;" // C3 & C4 addr
        "vse64.v    v20,  (t1) ; sh3add  t0, %[ldc], t0;" // C4 & C5 addr
        "vse64.v    v21,  (t0) ; sh3add  t1, %[ldc], t1;" // C5 & C6 addr
        "vse64.v    v22,  (t1) ; sh3add  t0, %[ldc], t0;" // C6 & C7 addr
        "vse64.v    v23,  (t0) ;" // C7

        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc]"r"(ldc), [alpha]"f"(alpha)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}

static inline void X80_n4xm4_kernel(BLASLONG m, BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetvli   zero,%[m],e64,m1,ta,ma;"

        "vle64.v    v30, (%[A]);" // a0
        "sh3add     %[A], %[m], %[A];" // next a0 addr
        "fld        ft0,   (%[B]);" // b0
        "fld        ft1,  8(%[B]);" // b1
        "addi       %[bk], %[bk], -1;" // loop var

        "fld        ft2, 16(%[B]);" // b2
        "vfmul.vf   v0, v30, ft0;"

        "fld        ft3, 24(%[B]);" // b3
        "vfmul.vf   v1, v30, ft1;"

        
        "addi       %[B], %[B], 32;" // next b addr
        "vfmul.vf   v2, v30, ft2;"

        "vfmul.vf  v3, v30, ft3;"

        "dgemm_4x4_asm_k_loop%=:"       
            "beq        %[bk], zero, dgemm_4x4_asm_k_loop_finish%=;"
            "vle64.v    v30, (%[A]);" // a0
            "sh3add     %[A], %[m], %[A];" // next a0 addr
            "fld        ft0,   (%[B]);" // b0
            "fld        ft1,  8(%[B]);" // b1
            "addi       %[bk], %[bk], -1;" // loop var

            "fld        ft2, 16(%[B]);" // b2
            "vfmacc.vf  v0, ft0, v30;"

            "fld        ft3, 24(%[B]);" // b3
            "vfmacc.vf  v1, ft1, v30;"

            "addi       %[B], %[B], 32;" // next b addr
            "vfmacc.vf  v2, ft2, v30;"
            
            "vfmacc.vf  v3, ft3, v30;"
            
            "j          dgemm_4x4_asm_k_loop%=;"
        "dgemm_4x4_asm_k_loop_finish%=:"

        "vle64.v    v16, (%[C]); sh3add  t0, %[ldc], %[C];" // C0 & C1 addr
        "vle64.v    v17,  (t0) ; sh3add  t0, %[ldc], t0;" // C1 & C2 addr
        "vle64.v    v18,  (t0) ; sh3add  t0, %[ldc], t0;" // C2 & C3 addr
        "vle64.v    v19,  (t0) ;" // C3

        "vfmacc.vf v16, %[alpha], v0;"
        "vfmacc.vf v17, %[alpha], v1;"
        "vfmacc.vf v18, %[alpha], v2;"
        "vfmacc.vf v19, %[alpha], v3;"

        "vse64.v    v16, (%[C]); sh3add  t0, %[ldc], %[C];" // C0 & C1 addr
        "vse64.v    v17,  (t0) ; sh3add  t0, %[ldc], t0;" // C1 & C2 addr
        "vse64.v    v18,  (t0) ; sh3add  t0, %[ldc], t0;" // C2 & C3 addr
        "vse64.v    v19,  (t0) ;" // C3

        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc]"r"(ldc), [alpha]"f"(alpha), [m]"r"(m)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}


static inline void X80_n4xm1_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetivli  zero,4,e64,m1,ta,ma;"

        "fld       ft0,  (%[A]); addi    %[A], %[A], 8;"   // a0 & next a0 addr 
        "vle64.v   v31,  (%[B]); addi    %[B], %[B], 32;" // b0
        "vfmul.vf  v0, v31, ft0; addi    %[bk], %[bk], -1;" // b0

        "dgemm_4x1_asm_k_loop%=:"
            "beq       %[bk], zero, dgemm_4x1_asm_k_loop_finish%=;"
            "fld       ft0,  (%[A]) ; addi    %[A], %[A], 8;" // a0 & next a0 addr
            "vle64.v   v31,  (%[B]) ; addi    %[B], %[B], 32;" // b0 & loop var
            "addi      %[bk], %[bk], -1;"

            "vfmacc.vf  v0, ft0, v31;" // b0

            "j        dgemm_4x1_asm_k_loop%=;"
        "dgemm_4x1_asm_k_loop_finish%=:"

        "slli      t0, %[ldc], 3;"
        "vlse64.v  v16, (%[C]), t0;" // C0
        
        "vfmacc.vf v16, %[alpha], v0;"

        "vsse64.v  v16, (%[C]), t0;" // C0
        
        
        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc]"r"(ldc), [alpha]"f"(alpha)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}


static inline void X80_n2xm8_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetivli   zero,4,e64,m1,ta,ma;"
        "addi     t6, %[A], 32;" // a1 addr

        "vle64.v    v30, (%[A]);" // a0
        "addi       %[A], %[A], 64;" // next a0 addr
        "vle64.v    v31, (t6);"   // a1
        "addi       t6, t6, 64;"     // next a1 addr
        "fld        ft0,   (%[B]);" // b0
        "fld        ft1,  8(%[B]);" // b1
        "addi       %[bk], %[bk], -1;" // loop var

        "vfmul.vf   v0, v30, ft0;"
        "vfmul.vf   v1, v31, ft0;"

        "addi       %[B], %[B], 16;" // next b addr
        "vfmul.vf   v2, v30, ft1;"
        "vfmul.vf   v3, v31, ft1;"
        
        "dgemm_2x8_asm_k_loop%=:"
            "beq        %[bk], zero, dgemm_2x8_asm_k_loop_finish%=;"
            "vle64.v    v30, (%[A]);" // a0
            "addi       %[A], %[A], 64;" // next a0 addr
            "vle64.v    v31, (t6);"   // a1
            "addi       t6, t6, 64;"     // next a1 addr
            "fld        ft0,   (%[B]);" // b0
            "fld        ft1,  8(%[B]);" // b1
            "addi       %[bk], %[bk], -1;" // loop var

            "addi       %[B], %[B], 16;" // next b addr
            "vfmacc.vf   v0, ft0, v30;"
            "vfmacc.vf   v1, ft0, v31;"

            "vfmacc.vf   v2, ft1, v30;"
            "vfmacc.vf   v3, ft1, v31;"
            
            "j           dgemm_2x8_asm_k_loop%=;"
        "dgemm_2x8_asm_k_loop_finish%=:"

        "vle64.v    v16, (%[C]); addi    t0, %[C], 32  ;" // C0 & C1 addr
        "vle64.v    v17,  (t0) ; sh3add  t1, %[ldc], %[C];" // C1 & C2 addr
        "vle64.v    v18,  (t1) ; sh3add  t0, %[ldc], t0;" // C2 & C3 addr
        "vle64.v    v19,  (t0) ;" // C3

        "vfmacc.vf v16, %[alpha], v0;"
        "vfmacc.vf v17, %[alpha], v1;"
        "vfmacc.vf v18, %[alpha], v2;"
        "vfmacc.vf v19, %[alpha], v3;"

        "vse64.v    v16, (%[C]); addi    t0, %[C], 32  ;" // C0 & C1 addr
        "vse64.v    v17,  (t0) ; sh3add  t1, %[ldc], %[C];" // C1 & C2 addr
        "vse64.v    v18,  (t1) ; sh3add  t0, %[ldc], t0;" // C2 & C3 addr
        "vse64.v    v19,  (t0) ;" // C3

        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc]"r"(ldc), [alpha]"f"(alpha)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}

static inline void X80_n2xm4_kernel(BLASLONG m, BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetvli   zero,%[m],e64,m1,ta,ma;"

        "vle64.v    v30, (%[A]);" // a0
        "sh3add     %[A], %[m], %[A];" // next a0 addr
        "fld        ft0,   (%[B]);" // b0
        "fld        ft1,  8(%[B]);" // b1
        "addi       %[bk], %[bk], -1;" // loop var

        "vfmul.vf   v0, v30, ft0;"

        "addi       %[B], %[B], 16;" // next b addr
        "vfmul.vf   v1, v30, ft1;"
        
        "dgemm_2x4_asm_k_loop%=:"
            "beq        %[bk], zero, dgemm_2x4_asm_k_loop_finish%=;"
            "vle64.v    v30, (%[A]);" // a0
            "sh3add     %[A], %[m], %[A];" // next a0 addr
            "fld        ft0,   (%[B]);" // b0
            "fld        ft1,  8(%[B]);" // b1
            "addi       %[bk], %[bk], -1;" // loop var

            "vfmacc.vf  v0, ft0, v30;"

            "addi       %[B], %[B], 16;" // next b addr
            
            "vfmacc.vf  v1, ft1, v30;"
            
            "j          dgemm_2x4_asm_k_loop%=;"
            
        "dgemm_2x4_asm_k_loop_finish%=:"

        "vle64.v    v16, (%[C]); sh3add  t0, %[ldc], %[C];" // C0 & C1 addr
        "vle64.v    v17,  (t0) ;" // C1

        "vfmacc.vf v16, %[alpha], v0;"
        "vfmacc.vf v17, %[alpha], v1;"

        "vse64.v    v16, (%[C]); sh3add  t0, %[ldc], %[C];" // C0 & C1 addr
        "vse64.v    v17,  (t0) ;" // C1

        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc]"r"(ldc), [alpha]"f"(alpha), [m]"r"(m)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}

static inline void X80_n2xm1_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetivli  zero,2,e64,m1,ta,ma;"
        "fld       ft6, (%[A]);" // a0
        "addi      %[A], %[A], 8;" // next a0 addr
        "vle64.v   v0, (%[B]);" // b0
        "addi      %[bk], %[bk], -1;" // loop var

        "vfmul.vf  v0, v0, ft6;"

        "addi      %[B], %[B], 16;" // next b addr
        
        "dgemm_2x1_asm_k_loop%=:"
            "beq      %[bk], zero, dgemm_2x1_asm_k_loop_finish%=;"
            "fld      ft0, (%[A]);" // a0
            "addi     %[A], %[A], 8;" // next a0 addr
            "vle64.v  v31,   (%[B]);" // b0
            "addi     %[bk], %[bk], -1;" // loop var

            "vfmacc.vf  v0, ft0, v31;"

            "addi       %[B], %[B], 16;" // next b addr
            
            "j          dgemm_2x1_asm_k_loop%=;"
            
        "dgemm_2x1_asm_k_loop_finish%=:"

        "vlse64.v    v16, (%[C]), %[ldc8];" // C0

        "vfmacc.vf  v16, %[alpha], v0;"

        "vsse64.v    v16, (%[C]), %[ldc8];" // C0

        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc8]"r"(ldc*8), [alpha]"f"(alpha)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}


static inline void X80_n1xm8_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetivli   zero,4,e64,m1,ta,ma;"
        "addi     t6, %[A], 32;" // a1 addr

        "vle64.v    v30, (%[A]);" // a0
        "addi       %[A], %[A], 64;" // next a0 addr
        "vle64.v    v31, (t6);"   // a1
        "addi       t6, t6, 64;"     // next a1 addr
        "fld        ft0,   (%[B]);" // b0
        "addi       %[bk], %[bk], -1;" // loop var

        "vfmul.vf   v0, v30, ft0;"
        "vfmul.vf   v1, v31, ft0;"
        "addi       %[B], %[B], 8;" // next b addr
        
        "dgemm_1x8_asm_k_loop%=:"
            "beq        %[bk], zero, dgemm_1x8_asm_k_loop_finish%=;"
            "vle64.v    v30, (%[A]);" // a0
            "addi       %[A], %[A], 64;" // next a0 addr
            "vle64.v    v31, (t6);"   // a1
            "addi       t6, t6, 64;"     // next a1 addr
            "fld        ft0,   (%[B]);" // b0
            "fld        ft1,  8(%[B]);" // b1
            "addi       %[bk], %[bk], -1;" // loop var

            "addi       %[B], %[B], 8;" // next b addr
            "vfmacc.vf  v0, ft0, v30;"
            "vfmacc.vf  v1, ft0, v31;"
            
            "j          dgemm_1x8_asm_k_loop%=;"

        "dgemm_1x8_asm_k_loop_finish%=:"

        "vle64.v    v16, (%[C]); addi    t0, %[C], 32  ;" // C0 & C1 addr
        "vle64.v    v17,  (t0) ;" // 1

        "vfmacc.vf v16, %[alpha], v0;"
        "vfmacc.vf v17, %[alpha], v1;"

        "vse64.v    v16, (%[C]); addi    t0, %[C], 32  ;" // C0 & C1 addr
        "vse64.v    v17,  (t0) ;" // C1

        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc]"r"(ldc), [alpha]"f"(alpha)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}


static inline void X80_n1xm4_kernel(BLASLONG m, BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc){
    asm volatile(
        "vsetvli   zero,%[m],e64,m1,ta,ma;"

        "vle64.v    v30, (%[A]);" // a0
        "sh3add     %[A], %[m], %[A];" // next a0 addr
        "fld        ft0,   (%[B]);" // b0
        "addi       %[bk], %[bk], -1;" // loop var

        "vfmul.vf   v0, v30, ft0;"

        "addi       %[B], %[B], 8;" // next b addr

        "dgemm_1x4_asm_k_loop%=:"
            "beq        %[bk], zero, dgemm_1x4_asm_k_loop_finish%=;"
            "vle64.v    v30, (%[A]);" // a0
            "sh3add     %[A], %[m], %[A];" // next a0 addr
            "fld        ft0,   (%[B]);" // b0
            "addi       %[bk], %[bk], -1;" // loop var

            "vfmacc.vf  v0, ft0, v30;"

            "addi       %[B], %[B], 8;" // next b addr            
            "j          dgemm_1x4_asm_k_loop%=;"
            
        "dgemm_1x4_asm_k_loop_finish%=:"

        "vle64.v    v16, (%[C]);" // C0

        "vfmacc.vf  v16, %[alpha], v0;"

        "vse64.v    v16, (%[C]);" // C0

        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [ldc]"r"(ldc), [alpha]"f"(alpha), [m]"r"(m)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}


static inline void X80_dot_kernel(BLASLONG bk, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C){
    asm volatile(
        "vsetivli   zero,4,e64,m1,ta,ma;"
        "addi       t4, zero, 4;"

        "vxor.vv    v1, v1, v1;" // zero idiom
        "vxor.vv    v0, v0, v0;" // zero idiom
        "rvv_acc_loop%=:"
            "blt        %[bk], t4, rvv_acc_break%=;"
            "addi       %[bk], %[bk], -4;"
            "vle64.v    v2, (%[A]);"
            "vle64.v    v3, (%[B]);"
            "vfmacc.vv  v1, v2, v3;"
            "addi       %[A], %[A], 32;"
            "addi       %[B], %[B], 32;"
            "j          rvv_acc_loop%=;"
        "rvv_acc_break%=:"

        "vfredusum.vs  v1, v1, v0;"
        "vfmv.f.s      ft0, v1;"
        
        "scalar_acc_loop%=:"
            "beq        %[bk], zero, scalar_acc_break%=;"
            "addi       %[bk], %[bk], -1;"
            "fld        ft1, (%[A]);"
            "fld        ft2, (%[B]);"
            "addi       %[A], %[A], 8;"
            "addi       %[B], %[B], 8;"
            "fmadd.d    ft0, ft1, ft2, ft0;"
            "j          scalar_acc_loop%=;"
        "scalar_acc_break%=:"

        
        "fld      ft1, (%[C]);"
        "fmadd.d  ft1, ft0, %[alpha], ft1;"
        "fsd      ft1, (%[C]);"

        : [A]"+r"(A), [B]"+r"(B), [bk]"+r"(bk)
        : [C]"r"(C),  [alpha]"f"(alpha)
        : "memory",
        "t0","t1","t2","t3","t4","t5","t6",
        "v0","v1","v2","v3","v4","v5","v6","v7",
        "v8","v9","v10","v11","v12","v13","v14","v15",
        "v16","v17","v18","v19","v20","v21","v22","v23",
        "v24","v25","v26","v27","v28","v29","v30","v31",
        "ft0","ft1","ft2","ft3","ft4","ft5","ft6","ft7"
    );
}